language: python

matrix:
  allow_failures:
  - python: nightly
  - python: 3.6-dev
  include:
  - python: 3.5
  - python: 3.4
  - python: 2.7
  - python: pypy
  - python: pypy3
  - python: 3.6-dev
  - python: nightly
  - language: java
    jdk: oraclejdk8
    env: TESTLANG=java
  - language: java
    jdk: oraclejdk7
    env: TESTLANG=java


before_script:
- env
- if [ "$TESTLANG" != java ]; then pip install . pytest; fi

script:
- env
- if [ "$TESTLANG" == java ]; then
    mvn test;
  else
    py.test -v -s python/tests;
  fi
