language: python
python:
- 3.5
- 3.4
- 2.7
- pypy
- pypy3
- 3.6-dev
- nightly

matrix:
  allow_failures:
  - python: nightly
  - python: 3.6-dev

before_script:
- pip install . pytest

script:
- py.test -v -s python/tests
- mvn test

